# Generated by Django 3.1.4 on 2021-01-05 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='tweet_id',
            new_name='tweet',
        ),
    ]
